# 1. Install packages

In [1]:
# pip install yfinance transformers torch
# pip install newsapi-python

# 2. Import Libraries

In [2]:
import yfinance as yf
import pandas as pd
import numpy as np
import datetime
import matplotlib.pyplot as plt
import seaborn as sns
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

# 3. Read Data

In [3]:
tickers = ['AAPL', 'MSFT', 'AMZN', 'GOOG'] 
# 'sp500', 'nasdaq', 'dowjones', 'ftse100', 'nikkei225', 'hangseng', 'dax', 'cac40', 'aex', 'bel20', 
# 'ibex35', 'psi20', 'sensex', 'asx200', 'kospi', 'twii'
start_date = '2000-01-01'
end_date = '2025-01-01'

In [4]:
import yfinance as yf
stock_data_hourly = yf.download(tickers=tickers, period='2y', interval='1h')  
print(f"\n shape: {stock_data_hourly.shape}\n\n cols: \n{stock_data_hourly.columns}\n ")
print(f"\n {stock_data_hourly.head(10)}")
print(f"\n {stock_data_hourly.tail(10)}")

YF.download() has changed argument auto_adjust default to True

[*********************100%***********************]  4 of 4 completed

 shape: (3494, 20)

 cols:
MultiIndex([( 'Close', 'AAPL'),
            ( 'Close', 'AMZN'),
            ( 'Close', 'GOOG'),
            ( 'Close', 'MSFT'),
            (  'High', 'AAPL'),
            (  'High', 'AMZN'),
            (  'High', 'GOOG'),
            (  'High', 'MSFT'),
            (   'Low', 'AAPL'),
            (   'Low', 'AMZN'),
            (   'Low', 'GOOG'),
            (   'Low', 'MSFT'),
            (  'Open', 'AAPL'),
            (  'Open', 'AMZN'),
            (  'Open', 'GOOG'),
            (  'Open', 'MSFT'),
            ('Volume', 'AAPL'),
            ('Volume', 'AMZN'),
            ('Volume', 'GOOG'),
            ('Volume', 'MSFT')],
           names=['Price', 'Ticker'])


 Price                           Close                                      \
Ticker                           AAPL        AMZN        GOOG        MSFT
Datetime
2023-05-03 13:30:00+00:00  170.080093  104.720001  106.325302  304.320007
2023-05-03 14:30:00+00:00  169.304993  104.834999  106.449997  306.359985
2023-05-03 15:30:00+00:00  169.699997  105.108803  106.550003  306.189911
2023-05-03 16:30:00+00:00  170.160004  105.019997  106.620003  307.239990
2023-05-03 17:30:00+00:00  170.244995  105.450104  107.450500  307.739990
2023-05-03 18:30:00+00:00  168.149994  103.675003  106.389999  304.660004
2023-05-03 19:30:00+00:00  167.460007  103.660004  106.120003  304.420013
2023-05-04 13:30:00+00:00  165.250000  103.449997  104.860001  303.750000
2023-05-04 14:30:00+00:00  165.934998  104.599998  105.669998  306.010010
2023-05-04 15:30:00+00:00  166.210007  104.410004  105.549004  306.350006

Price                            High                                      \
Ticker                           AAPL        AMZN        GOOG        MSFT
Datetime
2023-05-03 13:30:00+00:00  170.919998  105.959999  106.839996  306.899994
2023-05-03 14:30:00+00:00  170.279999  105.199997  106.605003  306.466095
2023-05-03 15:30:00+00:00  169.949997  105.150002  106.754997  306.973389
2023-05-03 16:30:00+00:00  170.289993  105.320000  106.672997  307.539886
2023-05-03 17:30:00+00:00  170.600006  105.714996  107.540001  308.470001
2023-05-03 18:30:00+00:00  170.759995  105.739998  108.129997  308.609985
2023-05-03 19:30:00+00:00  168.219894  103.830002  106.510002  305.170013
2023-05-04 13:30:00+00:00  165.770004  105.389999  106.300003  306.500000
2023-05-04 14:30:00+00:00  166.880005  104.930000  105.730003  306.600006
2023-05-04 15:30:00+00:00  166.229996  104.940002  105.739998  306.920013

Price                             Low                                      \
Ticker                           AAPL        AMZN        GOOG        MSFT
Datetime
2023-05-03 13:30:00+00:00  169.490005  103.580002  105.620003  304.260010
2023-05-03 14:30:00+00:00  169.179993  104.370003  106.209999  304.359985
2023-05-03 15:30:00+00:00  169.229996  104.461601  106.309998  305.329987
2023-05-03 16:30:00+00:00  169.570007  104.870003  106.300003  305.970001
2023-05-03 17:30:00+00:00  169.369995  104.449997  106.290001  306.070007
2023-05-03 18:30:00+00:00  168.119995  103.639999  106.360001  304.570007
2023-05-03 19:30:00+00:00  167.160004  103.279999  106.019997  304.089996
2023-05-04 13:30:00+00:00  164.309998  103.311699  104.849998  303.399994
2023-05-04 14:30:00+00:00  165.130295  103.320000  104.699997  303.660004
2023-05-04 15:30:00+00:00  165.429993  104.070000  105.160004  305.010010

Price                            Open                                      \
Ticker                           AAPL        AMZN        GOOG        MSFT
Datetime
2023-05-03 13:30:00+00:00  169.500000  103.735001  106.220001  306.149994
2023-05-03 14:30:00+00:00  170.080002  104.709999  106.320000  304.359985
2023-05-03 15:30:00+00:00  169.309998  104.839996  106.440002  306.339996
2023-05-03 16:30:00+00:00  169.710007  105.110603  106.559998  306.195007
2023-05-03 17:30:00+00:00  170.159897  105.014999  106.629997  307.244995
2023-05-03 18:30:00+00:00  170.250000  105.459999  107.470001  307.769989
2023-05-03 19:30:00+00:00  168.139999  103.669998  106.389999  304.649994
2023-05-04 13:30:00+00:00  164.889999  104.040001  106.160004  306.239990
2023-05-04 14:30:00+00:00  165.255005  103.449997  104.864998  303.750000
2023-05-04 15:30:00+00:00  165.940002  104.606003  105.669998  306.010010

Price                        Volume
Ticker                         AAPL      AMZN     GOOG     MSFT
Datetime
2023-05-03 13:30:00+00:00  13862984  17601647  3055733  4168946
2023-05-03 14:30:00+00:00   5450759   7330252  1579152  2380094
2023-05-03 15:30:00+00:00   3962052   5953883  1231109  1794899
2023-05-03 16:30:00+00:00   4108514   5292575  1446011  1756902
2023-05-03 17:30:00+00:00   5903150   7173773  1759706  2375936
2023-05-03 18:30:00+00:00  11104300  11598426  3891283  4151637
2023-05-03 19:30:00+00:00   6914097   6593367  2097408  2465509
2023-05-04 13:30:00+00:00  16477924  12694550  4168075  4387139
2023-05-04 14:30:00+00:00   9036370   6733349  2489736  3030911
2023-05-04 15:30:00+00:00   5049232   4470741  2073080  2072431

 Price                           Close                                      \
Ticker                           AAPL        AMZN        GOOG        MSFT
Datetime
2025-05-01 17:30:00+00:00  212.779999  189.946396  163.380005  429.911407
2025-05-01 18:30:00+00:00  212.940002  191.684998  163.289993  429.989990
2025-05-01 19:30:00+00:00  212.830002  189.835007  162.759995  425.130005
2025-05-02 13:30:00+00:00  206.720001  189.610001  165.929993  437.850006
2025-05-02 14:30:00+00:00  204.900803  189.329895  165.574997  434.899994
2025-05-02 15:30:00+00:00  205.000000  192.028595  165.970001  437.130005
2025-05-02 16:30:00+00:00  204.699005  190.824997  165.784302  436.510010
2025-05-02 17:30:00+00:00  204.880005  190.945007  166.139999  436.210510
2025-05-02 18:30:00+00:00  204.759995  190.369995  165.875000  435.684998
2025-05-02 19:30:00+00:00  205.300003  190.000000  165.789993  435.100006

Price                            High                                      \
Ticker                           AAPL        AMZN        GOOG        MSFT
Datetime
2025-05-01 17:30:00+00:00  213.000000  190.320007  163.710007  431.140015
2025-05-01 18:30:00+00:00  213.199997  191.800003  163.690002  431.899994
2025-05-01 19:30:00+00:00  214.550003  191.807098  163.358994  430.380005
2025-05-02 13:30:00+00:00  206.819901  192.264999  165.979996  439.440002
2025-05-02 14:30:00+00:00  206.990005  191.199997  166.449905  437.899994
2025-05-02 15:30:00+00:00  206.580002  192.880005  166.210007  438.190002
2025-05-02 16:30:00+00:00  205.889999  192.419601  166.699997  438.170013
2025-05-02 17:30:00+00:00  205.830002  191.270004  166.250000  437.309998
2025-05-02 18:30:00+00:00  205.429993  191.429993  166.380005  436.730011
2025-05-02 19:30:00+00:00  205.500000  190.669998  166.039993  435.970001

Price                             Low                                      \
Ticker                           AAPL        AMZN        GOOG        MSFT
Datetime
2025-05-01 17:30:00+00:00  212.065002  189.369995  162.720001  427.964996
2025-05-01 18:30:00+00:00  212.300003  189.899994  163.000000  429.799988
2025-05-01 19:30:00+00:00  212.470001  189.649994  162.634995  424.920013
2025-05-02 13:30:00+00:00  202.160004  186.399994  163.660004  429.984985
2025-05-02 14:30:00+00:00  204.600006  188.119995  165.419998  434.179993
2025-05-02 15:30:00+00:00  204.860596  188.789993  165.344498  433.938202
2025-05-02 16:30:00+00:00  204.149994  190.300003  165.740295  436.109985
2025-05-02 17:30:00+00:00  204.699997  190.139999  165.679993  435.630096
2025-05-02 18:30:00+00:00  203.660004  189.664993  165.440002  434.769989
2025-05-02 19:30:00+00:00  203.889999  189.725006  165.399994  434.600006

Price                            Open                                      \
Ticker                           AAPL        AMZN        GOOG        MSFT
Datetime
2025-05-01 17:30:00+00:00  212.509995  189.934998  162.934998  429.095001
2025-05-01 18:30:00+00:00  212.789993  189.960007  163.389999  429.910004
2025-05-01 19:30:00+00:00  212.940002  191.684998  163.270004  429.989990
2025-05-02 13:30:00+00:00  206.089996  191.490005  164.990005  431.709991
2025-05-02 14:30:00+00:00  206.720001  189.639999  165.949997  437.890015
2025-05-02 15:30:00+00:00  204.919998  189.309998  165.580002  434.904999
2025-05-02 16:30:00+00:00  205.000000  192.020004  165.979996  437.130005
2025-05-02 17:30:00+00:00  204.699997  190.822006  165.779999  436.470001
2025-05-02 18:30:00+00:00  204.869995  190.945007  166.149994  436.195007
2025-05-02 19:30:00+00:00  204.759995  190.350006  165.870102  435.659607

Price                        Volume
Ticker                         AAPL      AMZN     GOOG      MSFT
Datetime
2025-05-01 17:30:00+00:00   2827555   4203506  1531539   3338250
2025-05-01 18:30:00+00:00   3941988   7530691  1617452   3458119
2025-05-01 19:30:00+00:00   7135104   8545036  2968858   5249357
2025-05-02 13:30:00+00:00  30704404  29613615  4307381  10160256
2025-05-02 14:30:00+00:00   9323215  10256946  2414296   3551306
2025-05-02 15:30:00+00:00   8718007  10187241  2062244   2746092
2025-05-02 16:30:00+00:00   7635353   6001225  1416505   1976788
2025-05-02 17:30:00+00:00   7087245   4815229  1012144   1822505
2025-05-02 18:30:00+00:00   8882491   4936332  1313811   3510278
2025-05-02 19:30:00+00:00   9990065   6168187  1920401   2775337

In [5]:
import yfinance as yf
# Intraday data (intervals less than "1d") is only available for the last 60 days 
stock_data_15min = yf.download(tickers=tickers, period="60d", interval="15m") 
print(f"\n shape: {stock_data_15min.shape}\n\n cols: \n{stock_data_15min.columns}\n ")
print(f"\n {stock_data_15min.head(10)}")
print(f"\n {stock_data_15min.tail(10)}")

[*********************100%***********************]  4 of 4 completed

 shape: (1560, 20)

 cols:
MultiIndex([( 'Close', 'AAPL'),
            ( 'Close', 'AMZN'),
            ( 'Close', 'GOOG'),
            ( 'Close', 'MSFT'),
            (  'High', 'AAPL'),
            (  'High', 'AMZN'),
            (  'High', 'GOOG'),
            (  'High', 'MSFT'),
            (   'Low', 'AAPL'),
            (   'Low', 'AMZN'),
            (   'Low', 'GOOG'),
            (   'Low', 'MSFT'),
            (  'Open', 'AAPL'),
            (  'Open', 'AMZN'),
            (  'Open', 'GOOG'),
            (  'Open', 'MSFT'),
            ('Volume', 'AAPL'),
            ('Volume', 'AMZN'),
            ('Volume', 'GOOG'),
            ('Volume', 'MSFT')],
           names=['Price', 'Ticker'])


 Price                           Close                                      \
Ticker                           AAPL        AMZN        GOOG        MSFT
Datetime
2025-02-06 14:30:00+00:00  233.389999  238.130402  191.429993  417.700012
2025-02-06 14:45:00+00:00  233.520004  237.445007  191.970001  417.239990
2025-02-06 15:00:00+00:00  232.929993  237.800003  192.764694  416.350006
2025-02-06 15:15:00+00:00  231.539993  237.190002  192.190002  417.040009
2025-02-06 15:30:00+00:00  231.729996  237.550003  192.070007  416.910004
2025-02-06 15:45:00+00:00  230.949905  237.410004  192.559998  417.029999
2025-02-06 16:00:00+00:00  231.580002  237.291000  192.794998  418.000000
2025-02-06 16:15:00+00:00  231.514999  237.570007  192.550003  417.664215
2025-02-06 16:30:00+00:00  231.524994  236.899704  192.395004  416.730011
2025-02-06 16:45:00+00:00  231.059998  236.220001  192.449997  416.760010

Price                            High                                      \
Ticker                           AAPL        AMZN        GOOG        MSFT
Datetime
2025-02-06 14:30:00+00:00  233.554993  239.500000  192.479904  417.850006
2025-02-06 14:45:00+00:00  233.800003  238.240005  192.190002  418.049988
2025-02-06 15:00:00+00:00  233.539993  237.899994  192.800003  417.359894
2025-02-06 15:15:00+00:00  232.940002  237.969894  193.169998  417.239899
2025-02-06 15:30:00+00:00  232.325607  237.910004  192.610001  417.831696
2025-02-06 15:45:00+00:00  231.779694  238.009995  192.649994  417.160004
2025-02-06 16:00:00+00:00  231.699997  237.679993  192.869995  418.029999
2025-02-06 16:15:00+00:00  231.899994  238.000000  192.845993  418.200012
2025-02-06 16:30:00+00:00  231.634995  237.585007  192.714996  417.640015
2025-02-06 16:45:00+00:00  231.604294  236.910004  192.539993  416.940002

Price                             Low                                      \
Ticker                           AAPL        AMZN        GOOG        MSFT
Datetime
2025-02-06 14:30:00+00:00  230.779297  237.250000  190.490005  414.089996
2025-02-06 14:45:00+00:00  232.919998  237.255005  191.339996  416.720093
2025-02-06 15:00:00+00:00  232.429993  236.669998  191.259995  416.279999
2025-02-06 15:15:00+00:00  231.389999  237.139999  191.820496  416.179993
2025-02-06 15:30:00+00:00  231.410004  236.899994  191.720001  416.399994
2025-02-06 15:45:00+00:00  230.425003  237.255005  191.979996  416.460114
2025-02-06 16:00:00+00:00  230.869995  237.130005  192.386002  417.010010
2025-02-06 16:15:00+00:00  231.400406  237.270004  192.220001  417.589386
2025-02-06 16:30:00+00:00  231.240097  236.880005  192.320007  416.730011
2025-02-06 16:45:00+00:00  230.919998  236.009995  192.201202  416.309998

Price                            Open                                      \
Ticker                           AAPL        AMZN        GOOG        MSFT
Datetime
2025-02-06 14:30:00+00:00  231.339996  238.268005  191.110001  414.385010
2025-02-06 14:45:00+00:00  233.399994  238.119995  191.380005  417.739990
2025-02-06 15:00:00+00:00  233.479996  237.419998  191.970001  417.225006
2025-02-06 15:15:00+00:00  232.919998  237.800003  192.750000  416.350006
2025-02-06 15:30:00+00:00  231.585007  237.199997  192.179993  417.059998
2025-02-06 15:45:00+00:00  231.779694  237.550003  192.086197  416.839996
2025-02-06 16:00:00+00:00  230.940002  237.380005  192.559998  417.040009
2025-02-06 16:15:00+00:00  231.589798  237.289993  192.800003  418.000000
2025-02-06 16:30:00+00:00  231.509995  237.574997  192.559998  417.635010
2025-02-06 16:45:00+00:00  231.520004  236.910004  192.399994  416.757812

Price                       Volume
Ticker                        AAPL     AMZN     GOOG     MSFT
Datetime
2025-02-06 14:30:00+00:00  3109823  4794498  3720605  1614751
2025-02-06 14:45:00+00:00  1593174  1667039  1059647   955670
2025-02-06 15:00:00+00:00  1101576  1671538  1238570   490542
2025-02-06 15:15:00+00:00  1114508  1980326   835590   438733
2025-02-06 15:30:00+00:00   910063  1294431   867091   525148
2025-02-06 15:45:00+00:00  1335846  1108135   799895   294575
2025-02-06 16:00:00+00:00   706567   971509   581690   488645
2025-02-06 16:15:00+00:00   646930  1002669   493108   463105
2025-02-06 16:30:00+00:00   522704   863993   416268   270050
2025-02-06 16:45:00+00:00   786778  1376807   418687   327071

 Price                           Close                                      \
Ticker                           AAPL        AMZN        GOOG        MSFT
Datetime
2025-05-02 17:30:00+00:00  205.441498  190.339996  165.880005  435.890015
2025-05-02 17:45:00+00:00  205.399994  190.389999  166.044998  436.600006
2025-05-02 18:00:00+00:00  205.259995  191.203094  166.119995  437.230011
2025-05-02 18:15:00+00:00  204.880005  190.945007  166.139999  436.210510
2025-05-02 18:30:00+00:00  205.335007  190.830002  166.250000  436.079987
2025-05-02 18:45:00+00:00  204.179993  190.169998  165.830002  435.565002
2025-05-02 19:00:00+00:00  203.704895  190.074997  165.750000  435.140015
2025-05-02 19:15:00+00:00  204.759995  190.369995  165.875000  435.684998
2025-05-02 19:30:00+00:00  204.335007  190.389999  165.839996  435.799988
2025-05-02 19:45:00+00:00  205.300003  190.000000  165.789993  435.100006

Price                            High                                      \
Ticker                           AAPL        AMZN        GOOG        MSFT
Datetime
2025-05-02 17:30:00+00:00  205.529999  191.059998  165.899994  436.561890
2025-05-02 17:45:00+00:00  205.830002  190.619995  166.050003  436.929993
2025-05-02 18:00:00+00:00  205.610001  191.270004  166.250000  437.309998
2025-05-02 18:15:00+00:00  205.255005  191.269608  166.240005  437.230011
2025-05-02 18:30:00+00:00  205.360001  191.429993  166.380005  436.730011
2025-05-02 18:45:00+00:00  205.429993  190.879807  166.259995  436.139099
2025-05-02 19:00:00+00:00  204.350494  190.279999  165.869995  435.664490
2025-05-02 19:15:00+00:00  204.981506  190.479996  166.100006  435.869995
2025-05-02 19:30:00+00:00  205.154404  190.580002  165.960007  435.970001
2025-05-02 19:45:00+00:00  205.500000  190.669998  166.039993  435.894989

Price                             Low                                      \
Ticker                           AAPL        AMZN        GOOG        MSFT
Datetime
2025-05-02 17:30:00+00:00  204.699997  190.139999  165.679993  435.630096
2025-05-02 17:45:00+00:00  204.850006  190.160004  165.729996  435.799988
2025-05-02 18:00:00+00:00  205.160004  190.160004  166.009995  436.495300
2025-05-02 18:15:00+00:00  204.820007  190.710007  166.039993  436.144409
2025-05-02 18:30:00+00:00  204.631607  190.809998  166.120102  435.903503
2025-05-02 18:45:00+00:00  204.095993  189.940002  165.684998  434.769989
2025-05-02 19:00:00+00:00  203.684998  189.664993  165.440002  434.829987
2025-05-02 19:15:00+00:00  203.660004  190.000504  165.712799  435.049988
2025-05-02 19:30:00+00:00  204.259995  189.899994  165.710007  435.149994
2025-05-02 19:45:00+00:00  203.889999  189.725006  165.399994  434.600006

Price                            Open                                      \
Ticker                           AAPL        AMZN        GOOG        MSFT
Datetime
2025-05-02 17:30:00+00:00  204.699997  190.822006  165.779999  436.470001
2025-05-02 17:45:00+00:00  205.449997  190.350006  165.889999  435.899994
2025-05-02 18:00:00+00:00  205.389999  190.389999  166.029999  436.570007
2025-05-02 18:15:00+00:00  205.254501  191.196503  166.115494  437.230011
2025-05-02 18:30:00+00:00  204.869995  190.945007  166.149994  436.195007
2025-05-02 18:45:00+00:00  205.335007  190.839996  166.250000  436.079987
2025-05-02 19:00:00+00:00  204.169998  190.149994  165.835007  435.565002
2025-05-02 19:15:00+00:00  203.699997  190.061600  165.740005  435.130005
2025-05-02 19:30:00+00:00  204.759995  190.350006  165.870102  435.659607
2025-05-02 19:45:00+00:00  204.335007  190.399994  165.850006  435.829987

Price                       Volume
Ticker                        AAPL     AMZN     GOOG     MSFT
Datetime
2025-05-02 17:30:00+00:00  1277955  1065494   259071   428307
2025-05-02 17:45:00+00:00  3121090  1082705   275873   567330
2025-05-02 18:00:00+00:00  1238074  1582317   242423   435387
2025-05-02 18:15:00+00:00  1450126  1084713   234777   391481
2025-05-02 18:30:00+00:00  2085949   958255   254377   450780
2025-05-02 18:45:00+00:00  2091789  1332345   337259   537254
2025-05-02 19:00:00+00:00  2484827  1309781   374725  1940748
2025-05-02 19:15:00+00:00  2219926  1335951   347450   581496
2025-05-02 19:30:00+00:00  3438147  1740374   513871   604312
2025-05-02 19:45:00+00:00  6551918  4427813  1406530  2171025

In [6]:
# Read data from Yahoo Finance
def read_data(tickers, start_date, end_date):
    df = yf.download(tickers=tickers, start=start_date, end=end_date, progress=True)
    print(f"\n shape: {df.shape}\n\n cols: \n{df.columns}\n {df.head(10)}")
    return df
df_prices = read_data(tickers, start_date, end_date)

[*********************100%***********************]  4 of 4 completed

 shape: (6289, 20)

 cols:
MultiIndex([( 'Close', 'AAPL'),
            ( 'Close', 'AMZN'),
            ( 'Close', 'GOOG'),
            ( 'Close', 'MSFT'),
            (  'High', 'AAPL'),
            (  'High', 'AMZN'),
            (  'High', 'GOOG'),
            (  'High', 'MSFT'),
            (   'Low', 'AAPL'),
            (   'Low', 'AMZN'),
            (   'Low', 'GOOG'),
            (   'Low', 'MSFT'),
            (  'Open', 'AAPL'),
            (  'Open', 'AMZN'),
            (  'Open', 'GOOG'),
            (  'Open', 'MSFT'),
            ('Volume', 'AAPL'),
            ('Volume', 'AMZN'),
            ('Volume', 'GOOG'),
            ('Volume', 'MSFT')],
           names=['Price', 'Ticker'])
 Price          Close                                High                 \
Ticker          AAPL      AMZN GOOG       MSFT      AAPL      AMZN GOOG
Date
2000-01-03  0.842151  4.468750  NaN  35.792313  0.846382  4.478125  NaN
2000-01-04  0.771149  4.096875  NaN  34.583229  0.832276  4.575000  NaN
2000-01-05  0.782433  3.487500  NaN  34.947872  0.831806  3.756250  NaN
2000-01-06  0.714723  3.278125  NaN  33.777187  0.805004  3.634375  NaN
2000-01-07  0.748578  3.478125  NaN  34.218594  0.759864  3.525000  NaN
2000-01-10  0.735413  3.459375  NaN  34.468079  0.769267  3.631250  NaN
2000-01-11  0.697795  3.337500  NaN  33.585285  0.747638  3.500000  NaN
2000-01-12  0.655947  3.178125  NaN  32.491360  0.718485  3.400000  NaN
2000-01-13  0.727889  3.296875  NaN  33.105484  0.742935  3.359375  NaN
2000-01-14  0.755631  3.212500  NaN  34.468079  0.769267  3.431250  NaN

Price                       Low                                Open            \
Ticker           MSFT      AAPL      AMZN GOOG       MSFT      AAPL      AMZN
Date
2000-01-03  36.425635  0.765036  3.952344  NaN  34.391327  0.789017  4.075000
2000-01-04  35.965023  0.761274  4.087500  NaN  34.468080  0.814408  4.268750
2000-01-05  35.734727  0.774910  3.400000  NaN  33.585270  0.780552  3.525000
2000-01-06  34.967066  0.714723  3.200000  NaN  33.278206  0.798421  3.565625
2000-01-07  34.468084  0.718485  3.309375  NaN  32.951949  0.726008  3.350000
2000-01-10  34.909485  0.712842  3.278125  NaN  34.199396  0.767387  3.628125
2000-01-11  35.082229  0.680868  3.250000  NaN  33.374178  0.721776  3.343750
2000-01-12  33.431748  0.650774  3.150000  NaN  32.069145  0.714723  3.393750
2000-01-13  33.354975  0.695915  3.156250  NaN  31.167134  0.710843  3.246875
2000-01-14  34.986251  0.747638  3.200000  NaN  32.472154  0.752340  3.337500

Price                           Volume
Ticker     GOOG       MSFT        AAPL       AMZN GOOG      MSFT
Date
2000-01-03  NaN  36.041803   535796800  322352000  NaN  53228400
2000-01-04  NaN  34.871103   512377600  349748000  NaN  54119000
2000-01-05  NaN  34.122634   778321600  769148000  NaN  64059600
2000-01-06  NaN  34.448893   767972800  375040000  NaN  54976600
2000-01-07  NaN  33.354972   460734400  210108000  NaN  62013600
2000-01-10  NaN  34.832719   505064000  295158000  NaN  44963600
2000-01-11  NaN  34.237799   441548800  210654000  NaN  46743600
2000-01-12  NaN  33.316598   976068800  216090000  NaN  66532400
2000-01-13  NaN  32.049947  1032684800  208962000  NaN  83144000
2000-01-14  NaN  32.913561   390376000  137072000  NaN  73416400

In [7]:
# tickers = ['AAPL', 'MSFT']
# start_date = "2000-01-01"
# end_date = "2025-01-01"
# df_prices = yf.download(tickers=tickers, start=start_date, end=end_date, progress=True)
# df_prices.head(10)

In [8]:
# df_prices = df_prices[["Open","High","Low","Close","Volume"]]
df_prices.head(10)

Price          Close                                High                 \
Ticker          AAPL      AMZN GOOG       MSFT      AAPL      AMZN GOOG
Date
2000-01-03  0.842151  4.468750  NaN  35.792313  0.846382  4.478125  NaN
2000-01-04  0.771149  4.096875  NaN  34.583229  0.832276  4.575000  NaN
2000-01-05  0.782433  3.487500  NaN  34.947872  0.831806  3.756250  NaN
2000-01-06  0.714723  3.278125  NaN  33.777187  0.805004  3.634375  NaN
2000-01-07  0.748578  3.478125  NaN  34.218594  0.759864  3.525000  NaN
2000-01-10  0.735413  3.459375  NaN  34.468079  0.769267  3.631250  NaN
2000-01-11  0.697795  3.337500  NaN  33.585285  0.747638  3.500000  NaN
2000-01-12  0.655947  3.178125  NaN  32.491360  0.718485  3.400000  NaN
2000-01-13  0.727889  3.296875  NaN  33.105484  0.742935  3.359375  NaN
2000-01-14  0.755631  3.212500  NaN  34.468079  0.769267  3.431250  NaN

Price                       Low                                Open            \
Ticker           MSFT      AAPL      AMZN GOOG       MSFT      AAPL      AMZN
Date
2000-01-03  36.425635  0.765036  3.952344  NaN  34.391327  0.789017  4.075000
2000-01-04  35.965023  0.761274  4.087500  NaN  34.468080  0.814408  4.268750
2000-01-05  35.734727  0.774910  3.400000  NaN  33.585270  0.780552  3.525000
2000-01-06  34.967066  0.714723  3.200000  NaN  33.278206  0.798421  3.565625
2000-01-07  34.468084  0.718485  3.309375  NaN  32.951949  0.726008  3.350000
2000-01-10  34.909485  0.712842  3.278125  NaN  34.199396  0.767387  3.628125
2000-01-11  35.082229  0.680868  3.250000  NaN  33.374178  0.721776  3.343750
2000-01-12  33.431748  0.650774  3.150000  NaN  32.069145  0.714723  3.393750
2000-01-13  33.354975  0.695915  3.156250  NaN  31.167134  0.710843  3.246875
2000-01-14  34.986251  0.747638  3.200000  NaN  32.472154  0.752340  3.337500

Price                           Volume
Ticker     GOOG       MSFT        AAPL       AMZN GOOG      MSFT
Date
2000-01-03  NaN  36.041803   535796800  322352000  NaN  53228400
2000-01-04  NaN  34.871103   512377600  349748000  NaN  54119000
2000-01-05  NaN  34.122634   778321600  769148000  NaN  64059600
2000-01-06  NaN  34.448893   767972800  375040000  NaN  54976600
2000-01-07  NaN  33.354972   460734400  210108000  NaN  62013600
2000-01-10  NaN  34.832719   505064000  295158000  NaN  44963600
2000-01-11  NaN  34.237799   441548800  210654000  NaN  46743600
2000-01-12  NaN  33.316598   976068800  216090000  NaN  66532400
2000-01-13  NaN  32.049947  1032684800  208962000  NaN  83144000
2000-01-14  NaN  32.913561   390376000  137072000  NaN  73416400

In [9]:
# Flatten the multi-index: move 'Ticker' from columns to rows
df_flat = df_prices.stack(level=1).reset_index()
df_flat.columns
df_flat.head(10)

# Restructure and compute target columns
# df = df_prices['Open'].stack().reset_index()

# df.columns = ['Date', 'Ticker', 'Open']
# df['Close'] = df_prices['Close'].stack().values

# # Add other features
# for col in ['High', 'Low', 'Volume']:
#     df[col] = df_prices[col].stack().values

/var/folders/8w/vq_trrns7ml5vwfhcj8x1bk80000gq/T/ipykernel_31059/1975114513.py:2: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  df_flat = df_prices.stack(level=1).reset_index()

Index(['Date', 'Ticker', 'Close', 'High', 'Low', 'Open', 'Volume'], dtype='object', name='Price')

Price,Date,Ticker,Close,High,Low,Open,Volume
0,2000-01-03,AAPL,0.842151,0.846382,0.765036,0.789017,535796800.0
1,2000-01-03,AMZN,4.468750,4.478125,3.952344,4.075000,322352000.0
2,2000-01-03,MSFT,35.792313,36.425635,34.391327,36.041803,53228400.0
3,2000-01-04,AAPL,0.771149,0.832276,0.761274,0.814408,512377600.0
4,2000-01-04,AMZN,4.096875,4.575000,4.087500,4.268750,349748000.0
5,2000-01-04,MSFT,34.583229,35.965023,34.468080,34.871103,54119000.0
6,2000-01-05,AAPL,0.782433,0.831806,0.774910,0.780552,778321600.0
7,2000-01-05,AMZN,3.487500,3.756250,3.400000,3.525000,769148000.0
8,2000-01-05,MSFT,34.947872,35.734727,33.585270,34.122634,64059600.0
9,2000-01-06,AAPL,0.714723,0.805004,0.714723,0.798421,767972800.0

# create target column

In [10]:
# Step 2: Create the target column with next day's open price
df_flat['target_next_close'] = df_flat.groupby('Ticker')['Open'].shift(-1)
df_flat.head(10)

# df = df.sort_values(['Ticker', 'Date']).reset_index(drop=True)
# df['target_next_close'] = df.groupby('Ticker')['Close'].shift(-1)

Price,Date,Ticker,Close,High,Low,Open,Volume,target_next_close
0,2000-01-03,AAPL,0.842151,0.846382,0.765036,0.789017,535796800.0,0.814408
1,2000-01-03,AMZN,4.468750,4.478125,3.952344,4.075000,322352000.0,4.268750
2,2000-01-03,MSFT,35.792313,36.425635,34.391327,36.041803,53228400.0,34.871103
3,2000-01-04,AAPL,0.771149,0.832276,0.761274,0.814408,512377600.0,0.780552
4,2000-01-04,AMZN,4.096875,4.575000,4.087500,4.268750,349748000.0,3.525000
5,2000-01-04,MSFT,34.583229,35.965023,34.468080,34.871103,54119000.0,34.122634
6,2000-01-05,AAPL,0.782433,0.831806,0.774910,0.780552,778321600.0,0.798421
7,2000-01-05,AMZN,3.487500,3.756250,3.400000,3.525000,769148000.0,3.565625
8,2000-01-05,MSFT,34.947872,35.734727,33.585270,34.122634,64059600.0,34.448893
9,2000-01-06,AAPL,0.714723,0.805004,0.714723,0.798421,767972800.0,0.726008

In [11]:
df_flat.tail(5)

Price,Date,Ticker,Close,High,Low,Open,Volume,target_next_close
23989,2024-12-30,MSFT,423.979858,426.694417,421.055729,425.207408,13158700.0,425.247326
23990,2024-12-31,AAPL,250.144974,253.001833,249.156056,252.162760,39480700.0,NaN
23991,2024-12-31,AMZN,219.389999,223.229996,218.940002,222.970001,24819700.0,NaN
23992,2024-12-31,GOOG,190.223282,193.030082,189.364260,192.226005,14355200.0,NaN
23993,2024-12-31,MSFT,420.656525,425.876070,419.818209,425.247326,13246500.0,NaN

# Data cleaning

In [12]:
# Filter out rows where next_open is NaN (i.e., last record for each ticker)
# df_cleaned = df_flat[df_flat['target_next_open'].notna()].copy()
# Drop rows with missing target
df_cleaned = df_flat.dropna(subset=['target_next_close'])

# Reset index if needed
df_cleaned.reset_index(drop=True, inplace=True)
df_cleaned.head(10)
# # Show result
# print(df_cleaned[['Date', 'Ticker', 'Open', 'next_open']])

Price,Date,Ticker,Close,High,Low,Open,Volume,target_next_close
0,2000-01-03,AAPL,0.842151,0.846382,0.765036,0.789017,535796800.0,0.814408
1,2000-01-03,AMZN,4.468750,4.478125,3.952344,4.075000,322352000.0,4.268750
2,2000-01-03,MSFT,35.792313,36.425635,34.391327,36.041803,53228400.0,34.871103
3,2000-01-04,AAPL,0.771149,0.832276,0.761274,0.814408,512377600.0,0.780552
4,2000-01-04,AMZN,4.096875,4.575000,4.087500,4.268750,349748000.0,3.525000
5,2000-01-04,MSFT,34.583229,35.965023,34.468080,34.871103,54119000.0,34.122634
6,2000-01-05,AAPL,0.782433,0.831806,0.774910,0.780552,778321600.0,0.798421
7,2000-01-05,AMZN,3.487500,3.756250,3.400000,3.525000,769148000.0,3.565625
8,2000-01-05,MSFT,34.947872,35.734727,33.585270,34.122634,64059600.0,34.448893
9,2000-01-06,AAPL,0.714723,0.805004,0.714723,0.798421,767972800.0,0.726008

In [13]:
df_cleaned['Ticker'].value_counts()

Ticker
AAPL    6288
AMZN    6288
MSFT    6288
GOOG    5126
Name: count, dtype: int64

In [14]:
df_cleaned = df_cleaned[["Date", "Ticker", "Volume", "High","Low", "Open", "Close", "target_next_close"]]

# add more features

In [15]:
# Daily Return
df_cleaned['daily_return'] = (df_cleaned['Close'] - df_cleaned['Open']) / df_cleaned['Open']

# Moving Averages
df_cleaned['moving_avg_5'] = df_cleaned['Close'].rolling(window=5).mean()
df_cleaned['moving_avg_10'] = df_cleaned['Close'].rolling(window=10).mean()

# Volatility (Rolling Standard Deviation of Close)
df_cleaned['volatility_5'] = df_cleaned['Close'].rolling(window=5).std()

# Lag Features of `target_next_close` (simulate this column first)
df_cleaned['target_next_close'] = df_cleaned['Close'].shift(-1)
df_cleaned['target_next_close_lag1'] = df_cleaned['target_next_close'].shift(1)
df_cleaned['target_next_close_lag2'] = df_cleaned['target_next_close'].shift(2)

In [16]:
df_cleaned = df_cleaned.dropna()
# df_cleaned = df_flat.dropna(subset=['target_next_close'])
df_cleaned.head(100)

Price,Date,Ticker,Volume,High,Low,Open,Close,target_next_close,daily_return,moving_avg_5,moving_avg_10,volatility_5,target_next_close_lag1,target_next_close_lag2
9,2000-01-06,AAPL,767972800.0,0.805004,0.714723,0.798421,0.714723,3.278125,-0.104830,14.903151,12.048699,18.166725,0.714723,34.947872
10,2000-01-06,AMZN,375040000.0,3.634375,3.200000,3.565625,3.278125,33.777187,-0.080631,8.642131,12.292297,14.764429,3.278125,0.714723
11,2000-01-06,MSFT,54976600.0,34.967066,33.278206,34.448893,33.777187,0.748578,-0.019499,15.241081,15.223141,17.494420,33.777187,3.278125
12,2000-01-07,AAPL,460734400.0,0.759864,0.718485,0.726008,0.748578,3.478125,0.031088,14.693297,11.718767,17.990307,0.748578,33.777187
13,2000-01-07,AMZN,210108000.0,3.525000,3.309375,3.350000,3.478125,34.218594,0.038246,8.399348,11.989465,14.248402,3.478125,0.748578
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
104,2000-02-22,MSFT,66296200.0,29.823706,28.499488,29.209576,28.806553,0.874595,-0.013798,13.053767,13.098872,14.587734,28.806553,3.178125
105,2000-02-23,AAPL,473099200.0,0.895285,0.835097,0.851907,0.874595,3.521875,0.026631,12.581186,10.188606,15.017193,0.874595,28.806553
106,2000-02-23,AMZN,168824000.0,3.587500,3.234375,3.243750,3.521875,28.940914,0.085742,7.447481,10.454368,12.005153,3.521875,0.874595
107,2000-02-23,MSFT,75847200.0,29.401512,28.269209,28.710615,28.940914,0.866719,0.008021,13.064412,13.003459,14.467797,28.940914,3.521875
108,2000-02-24,AAPL,376432000.0,0.896225,0.840740,0.882589,0.866719,3.421875,-0.017981,12.602131,10.030992,14.893331,0.866719,28.940914

# save cleaned data for ML model

In [17]:
df_cleaned.to_csv('stock_prices_cleaned.csv', index=False)